// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtwkpmuyhpozbnacehcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0d2twbXV5aHBvemJuYWNlaGN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODY0MDAsImV4cCI6MjA2MzE2MjQwMH0.g_saKsT9hpLZ2AmY8PmwDxh468zwGQwa9fUfgFpOC8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);